substitutions:
  _PROJECT_ID: "second-broker-453913-b0"
  _REGION: "europe-west1"

steps:
  # Step 1: Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/backend/python-backend', './backend']

  # Step 2: Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/frontend/react-frontend', './frontend']

  # Step 3: Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/backend/python-backend']

  # Step 4: Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/frontend/react-frontend']

  # Step 5: Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--image=$_REGION-docker.pkg.dev/$_PROJECT_ID/backend/python-backend'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=5400'

  # Step 6: Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image=$_REGION-docker.pkg.dev/$_PROJECT_ID/frontend/react-frontend'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'

options:
  logging: CLOUD_LOGGING_ONLY
