substitutions:
  _PROJECT_ID: "second-broker-453913-b0"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/backend', './backend']

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/frontend', './frontend']

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/frontend']

  # Deploy Backend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./backend.yaml'
      - '--image=gcr.io/$_PROJECT_ID/backend'
      - '--cluster=cloudthon'
      - '--location=europe-west1'

  # Deploy Frontend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./frontend.yaml'
      - '--image=gcr.io/$_PROJECT_ID/frontend'
      - '--cluster=cloudthon'
      - '--location=europe-west1'

  
