substitutions:
  _PROJECT_ID: "second-broker-453913-b0"

options:
  logging: CLOUD_LOGGING_ONLY



  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/backend', './backend']

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/frontend', './frontend']

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/frontend']

  # Deploy Backend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./backend.yaml'
      - '--image=gcr.io/$_PROJECT_ID/backend'
      - '--cluster=cloudthon'
      - '--location=europe-west1'

  # Deploy Frontend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./frontend.yaml'
      - '--image=gcr.io/$_PROJECT_ID/frontend'
      - '--cluster=cloudthon'
      - '--location=europe-west1'

  # Run Security Scans
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'container', 'images', 'scan', 'gcr.io/$_PROJECT_ID/backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'container', 'images', 'scan', 'gcr.io/$_PROJECT_ID/frontend']

  # Enable Cloud Logging
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'services'
      - 'enable'
      - 'logging.googleapis.com'
      - '--project=$_PROJECT_ID'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'logging'
      - 'sinks'
      - 'create'
      - 'gke-logs'
      - 'storage.googleapis.com/$_PROJECT_ID-logs'
      - '--log-filter="resource.type=gke_cluster"'
      - '--format=json'
      - '--project=$_PROJECT_ID'

  # Apply IAM Role and Policy Updates
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'iam'
      - 'roles'
      - 'update'
      - 'custom_role1'
      - '--project=$_PROJECT_ID'
      - '--add-permissions=storage.buckets.get,storage.buckets.list'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'iam'
      - 'roles'
      - 'update'
      - 'custom_role2'
      - '--project=$_PROJECT_ID'
      - '--add-permissions=compute.instances.get,compute.instances.list'

timeout: 1200s
