substitutions:
  _PROJECT_ID: "second-broker-453913-b0"
  _REGION: "europe-west1"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Copy Service Account Key to /workspace/
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'cp ./keys/serviceaccount.json /workspace/service-account-key.json'

  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/backend/python-backend', './backend']
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account-key.json'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/frontend/react-frontend', './frontend']
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account-key.json'

  # Push Backend Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/backend/python-backend']

  # Push Frontend Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/frontend/react-frontend']

  # Deploy Frontend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./frontend.yaml'
      - '--cluster=cloudthon'
      - '--location=$_REGION'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account-key.json'

  # Deploy Backend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./backend.yaml'
      - '--cluster=cloudthon'
      - '--location=$_REGION'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account-key.json'
