substitutions:
  _PROJECT_ID: "second-broker-453913-b0"

steps:
  # Create GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'create'
      - 'my-cluster'
      - '--zone=us-central1-a'
      - '--num-nodes=3'
      - '--machine-type=e2-standard-4'
      - '--enable-autoscaling'
      - '--min-nodes=1'
      - '--max-nodes=5'
      - '--enable-network-policy'
      - '--enable-ip-alias'

  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/backend', './backend']

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/frontend', './frontend']

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/frontend']

  # Deploy Backend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./backend.yaml'
      - '--image=gcr.io/$_PROJECT_ID/backend'
      - '--cluster=my-cluster'
      - '--location=us-central1'

  # Deploy Frontend to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./frontend.yaml'
      - '--image=gcr.io/$_PROJECT_ID/frontend'
      - '--cluster=my-cluster'
      - '--location=us-central1'

  # Run Security Scans
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'container', 'images', 'scan', 'gcr.io/$_PROJECT_ID/backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'container', 'images', 'scan', 'gcr.io/$_PROJECT_ID/frontend']

  # Apply IAM Role and Policy Updates
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'iam'
      - 'roles'
      - 'update'
      - 'custom_role
